# Generated by Django 3.0.7 on 2020-07-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ram', max_length=100)),
                ('address', models.CharField(default='ram', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='ram', max_length=100)),
                ('l_name', models.CharField(default='ram', max_length=100)),
                ('address', models.CharField(default='ram', max_length=100)),
                ('naikename', models.CharField(default='ram', max_length=100)),
                ('naikelastname', models.CharField(default='ram', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('country', models.CharField(default='nepal', max_length=100)),
                ('district', models.CharField(max_length=100, null=True)),
                ('municipality', models.CharField(max_length=100, null=True)),
                ('ward', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(default=9999999999)),
                ('workercategory', models.CharField(max_length=100, null=True)),
                ('kiln', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapiapp.Kiln')),
            ],
        ),
    ]
