# Generated by Django 3.0.7 on 2020-08-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='children',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='extra',
        ),
    ]
