# Generated by Django 3.0.7 on 2020-08-10 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='naikelastname',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='naikename',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='workercategory',
            new_name='naike_f_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='author',
        ),
        migrations.AddField(
            model_name='workers',
            name='children',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='naike_l_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='naike_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
