# Generated by Django 3.0.7 on 2020-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0003_auto_20200811_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='naike_f_name',
            new_name='naike_name',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='naike_l_name',
            new_name='org',
        ),
        migrations.AddField(
            model_name='ngos',
            name='uuid',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='workers',
            name='duplicate',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ngos',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
