# Generated by Django 3.0.7 on 2020-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0003_auto_20200728_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiln',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='country',
        ),
        migrations.AlterField(
            model_name='workers',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10, null=True),
        ),
    ]
