# Generated by Django 3.0.7 on 2020-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0004_auto_20200917_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='duplicate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
