# Generated by Django 3.0.7 on 2020-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0005_auto_20200918_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiln',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kiln',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
