# Generated by Django 3.0.7 on 2020-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0006_auto_20200918_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='f_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
    ]
